# Generated by Django 3.1.4 on 2021-10-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211027_1307'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='unique_follower',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_follower',
            new_name='user_to_follow',
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.UniqueConstraint(fields=('user', 'user_to_follow'), name='unique_follower'),
        ),
    ]
